[package]
name = "omniverse/ovhl-framework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.3.0"
topbarplus = "1foreverhd/topbarplus@3.4.0"
onyx-ui = "imavafe/onyx-ui@1.0.2"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
profileservice = "brittonfischer/profileservice@2.1.5"
Option = "sleitnick/option@1.0.0"
Trove = "sleitnick/trove@1.3.0"
