[package]
name = "omniverse/ovhl-framework"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# [[ CORE UTILITIES - GUARANTEED ]]
TestEZ = "roblox/testez@0.4.1"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.3.0"
Option = "sleitnick/option@1.0.0"

# [[ DATA & INTEGRATION - GUARANTEED ]]
ProfileService = "brittonfischer/profileservice@2.1.5"
TopbarPlus = "1foreverhd/topbarplus@3.4.0"

# [[ REACT CORE ONLY ]]
# Kita hapus ReactSpring dan Reflex. Cukup engine utamanya.
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"